# Site settings
title: SHNITSEL
email: carolin.mueller@ext.uni.lu
url: https://compphotochem.github.io/
description: "Awesome description about our databse on excited states named SHnitzel "
skills: "Excited State - Photochemical Reactions - Photodynamics - ..."
meta_author: CECAM 2023, Vienna (x, y, and z)

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Carolin Müller
  location: Contributors
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: github
    url: https://github.com/CompPhotoChem/CompPhotoChem.github.io

# Postal address (add as many lines as necessary)
address:
  - line: Rachel Crespo-Otero
  - line: Steven Lopez
  - line: Carolin Müller

# Credits content
credits: 'This database was created during a collaboration in a CECAM workshop and is freely available.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
