# Site settings
title: SHNITSEL
email: carolin.mueller@ext.uni.lu
url: https://compphotochem.github.io/
description: "Surface Hopping Newly Invented Training Set for Excited-state Learning "
        
keywords: "– Excited States – Photochemical Reactions – Photodynamics –"
meta_author: CECAM 2023, Vienna

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: C4A000 # '252,233,79' #18bc9c #80B3FF (lighter version of yellow: FFE94F)
  primary-rgb: "252,233,79" #"24,288,156" #"128,179,255"
  secondary: 2c3e50 # '44,62,80' #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Carolin Müller
  location: About
  social: Meet Us
  credits: Contribute

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: github
    url: https://github.com/SHNITSEL

# Postal address (add as many lines as necessary)
address:
  - line: <a href="/cite-shnitsel/">Cite SHNITSEL</a>
  - line: <a href="/terms-of-use/">Terms of Use</a>
  - line: <a href="/impressum/">Impressum</a>

# Credits content
credits: <a href="https://github.com/SHNITSEL/contribute" style="color:white">Github</a><br><a href="https://github.com/SHNITSEL/contribute/issues/new" style="color:white">Create an Issue</a><br><a href"https://shnitsel.github.io/submit_data/" class="btn btn-lg btn-outline">Submit Data</a> 
#'This database was created during a collaboration in a CECAM workshop and is freely available.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
